version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/triad
    ldflags:
      - -s -w -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_arm64
      - darwin_amd64

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
